### ISSUE TITLE
Improve kwargs implementation

### ISSUE THREAD

**Issue by emdeh** [emdeh/pdf-document-processor#41]
# Getting started

- [x] Create a new development branch from `main` called `dev-kwargs-improvements`.
- [x] Pull the branch to your local repo.
- [x] Add descriptive commits for each task below as you work through them.
- [x] Regularly push the changes to the remote `dev-kwargs-improvements` branch.

> **_NB: You won't be able to test just yet as I broke a few key functions that the `process.py` uses. I will try to solve this soon, but otherwise we can review your changes together before you submit the Pull Request._**

## Files to work in
You will only need to modify the `process.py` and `postprocess.py` files.

# For `preprocess.py`:

> _The updates have already been completed for `preprocess.py`. You can use these as a reference._

- [x] Change kwargs implementation so `--output-folder` defaults to input folder and is not required to be passed.
- [x] Change `--statement_set_name` to be simpler
- [x] Update the description, create an epilog, and refine the help for each argument.

# For `process.py`:

## Task 1 - Remove the `--output-folder` argument.

- [x] Change the kwargs implementation so `--output-folder` is written inside the input folder like in `preprocess.py` within the below commit. This will mean the  `extracted-data.xlsx` file is written to a more logical location. 

1. Remove the argument from the parser:
https://github.com/emdeh/pdf-document-processor/blob/80e70e36da36e53d27078e10e164f26eb73712e2/src/process.py#L21

2. Update how the `output_folder` variable is set, so it is based on the given `input_folder`:
https://github.com/emdeh/pdf-document-processor/blob/80e70e36da36e53d27078e10e164f26eb73712e2/src/process.py#L27

> _See https://github.com/emdeh/pdf-document-processor/commit/6ffa706ca734d717b9823f5232689f9fd17d9d78#diff-bd9e96c493451832606e3dc0db09cecbfff190c255d509ff73ec2c8a5e62321cR16 for an example how this is achieved in the `preprocess.py` script._ 
> **_This is a link to a commit within another branch. The red lines are deletions, while the green lines are additions._**

## Task 2 - Make the `config_path` optional so it doesn't need to be passed every time.

- [x] Change `--config_path` to default to `config/type_models.yaml` and to be an optional argument so it does not have to be passed every time the script is run (but still can be in case in future a different config needs to be referenced.)

1. Update the `add_argument` in the parser:
https://github.com/emdeh/pdf-document-processor/blob/80e70e36da36e53d27078e10e164f26eb73712e2/src/process.py#L22

To be something like this:
```python
parser.add_argument(
    '--config_path',
    type=str,
    default='/config/type_models.yaml',
    help='Path to the statement types configuration YAML file (default: /config/type_models.yaml)'
)
```

> _As the script is always executed from the `src` folder, it should aways be able to find the yaml file at `/config` because `/src` and `/config` are in the same directory, so there is no need to pass it as an argument._

## Task 3 - Simplify argument names.

1. Update the `statement_type_name` `add_argument` in the parser:
https://github.com/emdeh/pdf-document-processor/blob/80e70e36da36e53d27078e10e164f26eb73712e2/src/process.py#L23

> _Perhaps something like `type` to more closely align to the variable in the `config.yaml` file._

2. Make sure to rename  the `statement_type_name` variable on L29, so it is correctly passed to the `select_statement_type()` method later. 
https://github.com/emdeh/pdf-document-processor/blob/80e70e36da36e53d27078e10e164f26eb73712e2/src/process.py#L29

3. Add a simpler parameter name for `--input_folder`, so it aligns to the changes in the `preprocess.py` commit and ensure to update how the renamed variable is set from the parser argument, so it is correctly passed to the relevant code later in runtime.

4. Consider also updating the `--confg_path` to be a shorter name (even though it will rarely be passed explicitly). And make sure it is 

## Task 4 - Update kwargs description and epilog for readability.

- [x] Update the description, create an epilog, and refine the help for each argument.

1. Consider updating the `parser.addargument()` formatting to enhance readability.
2. Update the help for each `parser.add_argument()` 

 For example, you could update them to look like this:
```python
    parser.add_argument(
        '-i', '--input',
        type=str,
        required=True,
        help='Path to the input folder containing PDFs that need to be split.'
        )
```

Instead of a single line like this:
```python
parser.add_argument('-i', '--input',type=str,required=True,help='Path to the input folder containing PDFs that need to be split.')
```

2. Update the `argparse.ArgumentParser(description=...` for the parser so it is more descriptive and includes an epilog with an example. See the `preprocess.py for clues`
https://github.com/emdeh/pdf-document-processor/blob/eb18271ecb3681dfa1f90def891c46c42c32fd9b/src/preprocess.py#L10-L20

# For `postprocess.py`:

## Task 1

- [x] Change the kwargs implementation so `--output-folder` is written inside the input folder like in `preprocess.py`. This will mean the excel file created from post-processing is always written to a more logical location (`output_folder` currently optional).

## Task 2

- [x] Add a simpler parameter name for `--input_folder`, so it aligns to the changes in the `preprocess.py` commit:
https://github.com/emdeh/pdf-document-processor/blob/eb18271ecb3681dfa1f90def891c46c42c32fd9b/src/preprocess.py#L23-L28

# Finishing up
Raise a Pull Request to pull your branch back into `main`.
